COLORS = %w[31 32 33 34 35 36]

class AntinodeFinder
  EMPTY = "."
  ANTINODE = "#"

  attr_reader :map, :size, :row_size, :antinodes, :colors
  def initialize(map)
    @map = map.reject { |d| d == "\n" }
    @size = @map.count
    @row_size = map.index("\n")
    @map.each_with_index do |freq, pos|
      frequencies[freq] << pos unless freq == EMPTY
    end
    @colors = @frequencies.keys.each_with_object({}).with_index do |(freq, h), i|
      h[freq] = COLORS[i % COLORS.length]
    end
    @antinodes = solve
  end

  def frequencies
    @frequencies ||= Hash.new { |h, k| h[k] = [] }
  end

  def show(freq = nil)
    @map.each_with_index do |cell, pos|
      print " "
      print "\n" if pos % row_size == 0
      if freq
        if @antinodes.fetch(pos, nil)&.include?(freq)
          print "\e[#{@colors[freq]}m#{ANTINODE}\e[0m"
        elsif cell == freq
          print "\e[#{@colors[freq]}m#{cell}\e[0m"
        else
          print EMPTY
        end
      elsif cell == EMPTY && @antinodes.keys.include?(pos)
        print "\e[#{@colors[@antinodes[pos].first]}m#{ANTINODE}\e[0m"
      else
        print "\e[#{@colors[cell]}m#{cell}\e[0m"
      end
    end
    print "\n"
    nil
  end

  def solve
    antinodes = Hash.new { |h, k| h[k] = [] }

    @frequencies.each do |frequency, positions|
      positions.combination(2) do |position|
        (a, b) = position.sort
        col_offset = ((b % row_size) - (a % @row_size)).abs

        doubled_dist = (b - a) * 2

        candidate_1 = b - ((b - a) * 2)
        candidate_2 = a + ((b - a) * 2)

        antinodes[candidate_1] << frequency if candidate_1 > 0 && candidate_1 < @size - 1 && ((b % @row_size) - (candidate_1 % @row_size)).abs == col_offset * 2
        antinodes[candidate_2] << frequency if candidate_2 > 0 && candidate_2 < @size - 1 && ((a % @row_size) - (candidate_2 % @row_size)).abs == col_offset * 2      end
    end
    antinodes
  end
end

af = AntinodeFinder.new(DATA.read.chars)
af.show
binding.irb


# .......... 09
# ...#...... 19 (# == 13)
# .......... 29
# ....a..... 39 (a == 34)
# .......... 49
# .....a.... 59 (a == 55)
# .......... 69
# ......#... 79 (# == 76)
# .......... 89
# .......... 99

__END__
.....................U.........w..................
l.................................................
...........o.a................U...w...............
............................................W.....
..........T....................s.............7....
.............................................W....
.........T..............4....n.d.H.........5......
......T.....oj...U.....n...w......H...........z...
.G..x..........................E.....V..H.........
.........a....................d....s.......7w.....
...j....r.............o.............V.......d...W.
.......r..J.Goa.U...............n................z
.........Jj.........M..........Pv.................
...J...........t..3..M..............sLV...........
...................t................n.............
....r...........X...........M........v............
...x....t......I......a.PM...............W........
...........1.Bj....I........vO.h.dL...............
.........6....Rr......B...X........h..5v.L..z.....
......1G...........x.....3B.......5...............
.................B....0..........4..E.............
.....................X.....5..h....P....f.....D...
.......1........J.....eK..........................
..................I....R....K...........k.........
......G..................O........................
...........H...9...............K8.P.4..k..E.......
............1....3.............8.F.............f..
.........................4........................
.l...........X............9.......................
....N.................R...t.e.....................
...g............3..R.........e....h.........f.....
...........................e......i...............
................2...I.7..9..O.....s.........k.....
....................6...9E.............F..O.......
........................KN........................
.......g......................Z.........F..f...Y..
...........................A....i.................
...........6g...b........8.......y.....S..........
..l.....6.....m...............8...................
....u..m...b...............p...A..................
..............b.p........................k........
....m......2...........Z..y....i..................
........g2.....b.........i....D..ZF...............
......2.0...........p............N..........A.....
...m.............S...y........A...Z...N...........
..S..l..........................................Y.
........S....0u.................y......DY.........
...........0.........................D............
.................u...................p...Y........
.......u..........................................
